### ISSUE TITLE
Install doesn't work (original AJT Japanese too)

### ISSUE THREAD

**Issue by lkalajzic** [arbyste/AJT-for-JPMN#1]
![image](https://github.com/arbyste/AJT-for-JPMN/assets/112662366/d28d7bb4-30b6-409e-845f-8e51dc3f28f8)

M1 Mac, newest (14.2.1 (23C71))

- The add-on crashes?
- The add-on stopped working?
- Have a feature request?

Don't forget to provide:

1) OS name
2) OS version
3) Anki version
4) Logs
5) Screenshots, if applicable

**Comment by arbyste** [comment]
I'm not able to reproduce this on the latest version of Anki (23.12.1). Both add ons install fine. Which version of Anki are you using?

**Comment by lkalajzic** [comment]
Ah frick, I thought I updated it. Sorry for the trouble.
